/*创建用户基本信息表*/
CREATE TABLE FX_USER_INFO(
  USER_ID VARCHAR (32) PRIMARY KEY ,
  USER_CN_NAME VARCHAR (50) NOT NULL ,
  USER_EN_NAME VARCHAR (50) ,
  USER_GENDER CHAR (2) NOT NULL CHECK (USER_GENDER IN ('男','女')),
  USER_IDENTITY_CARD VARCHAR (18) NOT NULL ,
  USER_IMAGE MEDIUMBLOB ,
  USER_PROV VARCHAR (20) NOT NULL ,
  USER_CITY VARCHAR (20) NOT NULL ,
  USER_REGION VARCHAR (50) NOT NULL ,
  USER_EMAIL VARCHAR (100) NOT NULL ,
  USER_PHONE VARCHAR (11)
);
/*创建唯一约束*/
ALTER TABLE FX_USER_INFO ADD UNIQUE (USER_IDENTITY_CARD);
ALTER TABLE FX_USER_INFO ADD UNIQUE (USER_EMAIL);


/*创建银行卡表*/
CREATE TABLE FX_BANKCARD(
  BANKCARD_ID VARCHAR (19) PRIMARY KEY ,
  BANKCARD_PASSWORD VARCHAR (100) NOT NULL ,
  BANKCARD_STATUS INT (2) NOT NULL ,
  BANKCARD_CREATED_TIME TIMESTAMP NOT NULL ,
  BANKCARD_CREATED_PLACE VARCHAR (150) NOT NULL ,
  USER_ID VARCHAR (32) NOT NULL ,
  FOREIGN KEY (USER_ID) REFERENCES FX_USER_INFO(USER_ID)
);
/*创建唯一约束*/
ALTER TABLE FX_BANKCARD ADD UNIQUE (USER_ID);


/*创建资产表*/
CREATE TABLE FX_ASSET(
  ASSET_ID VARCHAR (32) PRIMARY KEY ,
  CURRENCY_EN_NAME VARCHAR (20) NOT NULL ,
  FOREIGN KEY (CURRENCY_EN_NAME) REFERENCES FX_CURRENCY(CURRENCY_EN_NAME) ,
  ASSET_BALANCE DECIMAL (15,4) NOT NULL DEFAULT 0,
  BANKCARD_ID VARCHAR (19) NOT NULL ,
  FOREIGN KEY (BANKCARD_ID) REFERENCES FX_BANKCARD(BANKCARD_ID)
);
/*添加version字段==》乐观锁机制*/
ALTER TABLE FX_ASSET ADD VERSION int(11) NOT NULL DEFAULT 0;


/*创建交易记录表*/
CREATE TABLE FX_TRANSACTION_RECORD(
  TRANSACTION_ID VARCHAR (32) PRIMARY KEY ,
  BANKCARD_ID VARCHAR (19) NOT NULL ,
  FOREIGN KEY (BANKCARD_ID) REFERENCES FX_BANKCARD(BANKCARD_ID),
  TRANSACTION_MONEY DECIMAL (15,4) NOT NULL ,
  TRANSACTION_TYPE INT (2) NOT NULL ,
  CURRENCY_EN_NAME VARCHAR (20) NOT NULL ,
  FOREIGN KEY (CURRENCY_EN_NAME) REFERENCES FX_CURRENCY(CURRENCY_EN_NAME) ,
  TRANSACTION_TIME TIMESTAMP NOT NULL ,
  TRANSACTION_PLACE VARCHAR (150) ,
  TRANSACTION_PEOPLE VARCHAR (32) NOT NULL
);


/*创建货币表*/
CREATE TABLE FX_CURRENCY(
  CURRENCY_ID VARCHAR (32) PRIMARY KEY ,
  CURRENCY_CN_NAME VARCHAR (20) NOT NULL ,
  CURRENCY_EN_NAME VARCHAR (20) NOT NULL ,
  CURRENCY_COUNTRY VARCHAR (50) NOT NULL ,
  CURRENCY_DIR DECIMAL (6,4) NOT NULL ,
  CURRENCY_TDR_1 DECIMAL (6,4) ,
  CURRENCY_TDR_3 DECIMAL (6,4) ,
  CURRENCY_TDR_6 DECIMAL (6,4) ,
  CURRENCY_TDR_12 DECIMAL (6,4)
);
/*创建唯一约束*/
ALTER TABLE FX_CURRENCY ADD UNIQUE (CURRENCY_CN_NAME);
ALTER TABLE FX_CURRENCY ADD UNIQUE (CURRENCY_EN_NAME);


/*创建货币对表*/
CREATE TABLE FX_CURRENCY_PAIRS(
  CURRENCY_PAIRS_ID VARCHAR (32) PRIMARY KEY ,
  BASIC_CURRENCY VARCHAR (20) NOT NULL ,
  FOREIGN KEY (BASIC_CURRENCY) REFERENCES FX_CURRENCY(CURRENCY_EN_NAME) ,
  SECONDARY_CURRENCY VARCHAR (20) NOT NULL ,
  FOREIGN KEY (SECONDARY_CURRENCY) REFERENCES FX_CURRENCY(CURRENCY_EN_NAME)
);