spring:
  profiles:
    active: dev1
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
  mail:
    host: smtp.126.com
    username: gent_ni@126.com
    password: 126authcode
    default-encoding: utf-8