spring:
  profiles:
    active: dev1
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
    cache: false

  #≈‰÷√Redisµƒª∫¥Êπ‹¿Ì∆˜
  cache:
    cache-names: redisCache
    type: redis
  #redis≈‰÷√
  redis:
    port: 6379
    host: localhost
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
